"""update subtask many to many users

Revision ID: 6e22451093ec
Revises: 0a2eaad47964
Create Date: 2026-05-13 09:21:47.318443

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6e22451093ec'
down_revision = '0a2eaad47964'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sub_task', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('sub_task_assigned_to_fkey'), type_='foreignkey')
        batch_op.drop_column('assigned_to')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sub_task', schema=None) as batch_op:
        batch_op.add_column(sa.Column('assigned_to', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key(batch_op.f('sub_task_assigned_to_fkey'), 'user', ['assigned_to'], ['id'])

    # ### end Alembic commands ###
